# Generated by Django 2.1.4 on 2018-12-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprojects', '0002_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position', '-created_time']},
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
